# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './uis\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(2000, 1500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_upper = QtWidgets.QWidget(self.centralwidget)
        self.widget_upper.setStyleSheet("")
        self.widget_upper.setObjectName("widget_upper")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_upper)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.widget_search = QtWidgets.QWidget(self.widget_upper)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(16)
        self.widget_search.setFont(font)
        self.widget_search.setStyleSheet("border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black;")
        self.widget_search.setObjectName("widget_search")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_search)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_search = QtWidgets.QLineEdit(self.widget_search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_search.sizePolicy().hasHeightForWidth())
        self.input_search.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(16)
        self.input_search.setFont(font)
        self.input_search.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border-radius: 5px;")
        self.input_search.setText("")
        self.input_search.setReadOnly(False)
        self.input_search.setObjectName("input_search")
        self.horizontalLayout_3.addWidget(self.input_search)
        self.button_search = QtWidgets.QPushButton(self.widget_search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_search.sizePolicy().hasHeightForWidth())
        self.button_search.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(16)
        font.setUnderline(False)
        self.button_search.setFont(font)
        self.button_search.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 201, 252);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"border-color: rgb(255, 0, 255);\n"
"border-width:2px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 161, 255);\n"
"}")
        self.button_search.setObjectName("button_search")
        self.horizontalLayout_3.addWidget(self.button_search)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_5.addWidget(self.widget_search)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_5.setStretch(0, 3)
        self.verticalLayout_5.setStretch(2, 3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.widget_upper)
        self.widget_lower = QtWidgets.QWidget(self.centralwidget)
        self.widget_lower.setObjectName("widget_lower")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_lower)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_result = QtWidgets.QTableView(self.widget_lower)
        self.list_result.setStyleSheet("background-color:rgb(247, 255, 254);")
        self.list_result.setLineWidth(0)
        self.list_result.setObjectName("list_result")
        self.verticalLayout.addWidget(self.list_result)
        self.verticalLayout_2.addWidget(self.widget_lower)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Search Engine"))
        self.input_search.setPlaceholderText(_translate("MainWindow", "Input here."))
        self.button_search.setText(_translate("MainWindow", "Search"))
