# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './uis\warningwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarningWindow(object):
    def setupUi(self, WarningWindow):
        WarningWindow.setObjectName("WarningWindow")
        WarningWindow.resize(400, 300)
        WarningWindow.setStyleSheet("background-color: white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(WarningWindow)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_warning = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_warning.setFont(font)
        self.label_warning.setStyleSheet("font-weight:bold;")
        self.label_warning.setAlignment(QtCore.Qt.AlignCenter)
        self.label_warning.setObjectName("label_warning")
        self.verticalLayout.addWidget(self.label_warning)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setStyleSheet("border-color: black;")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.button_ok = QtWidgets.QPushButton(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(16)
        self.button_ok.setFont(font)
        self.button_ok.setStyleSheet("QPushButton{\n"
"border-radius: 2px;\n"
"border-width: 0.5px;\n"
"border-style: solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-color: rgb(255, 215, 248);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 240, 254);\n"
"}")
        self.button_ok.setObjectName("button_ok")
        self.verticalLayout_2.addWidget(self.button_ok)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.verticalWidget)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        WarningWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(WarningWindow)
        QtCore.QMetaObject.connectSlotsByName(WarningWindow)

    def retranslateUi(self, WarningWindow):
        _translate = QtCore.QCoreApplication.translate
        WarningWindow.setWindowTitle(_translate("WarningWindow", "Warning"))
        self.label_warning.setText(_translate("WarningWindow", "warning!"))
        self.button_ok.setText(_translate("WarningWindow", "   OK    "))
